# GLOBAL CONFIGURATION

from pynput.keyboard import Key, KeyCode

# COMMON
CONSOLE_WIDTH = 120
CONSOLE_UPDATE_FREQUENCY = 2
SWITCH_STATE_KEY = Key.home

# EVENT HANDLER
RUN_ON_STARTUP = True
ATTACH_TO_PROCESS = False
SILENT_MODE = False

# EVENT EMULATION
KB_EVENTS_SPEED_MULTIPLIER = 1
KB_PRESS_TIME = 65
KB_MAX_PRESS_TIME = 115
KB_RELEASE_TIME = 40
KB_MAX_RELEASE_TIME = 80
MS_EVENTS_SPEED_MULTIPLIER = 1
