# GLOBAL CONFIGURATION


# COMMON
SWITCH_STATE_KEY = 'home'
RUN_ON_STARTUP = False
SILENT_MODE = False
ATTACH_TO_PROCESS = True     # name of exe file
CONSOLE_UPDATE_FREQUENCY = 4 # per sec
CONSOLE_LOG_LEVEL = 3       # 0 - nothing, 1 - errors only, 2 - errors and warnings, 3 - all
CONSOLE_HIDE_CURSOR = True
CON_TOP_MARIN = 1
CON_LEFT_MARGIN = 3
CON_RIGHT_MARGIN = 1
CON_BOTTOM_MARGIN = 0

# EVENT EMULATION
KB_EVENTS_SPEED_MULTIPLIER = 1
KB_PRESS_TIME = 65
KB_MAX_PRESS_TIME = 115
KB_RELEASE_TIME = 40
KB_MAX_RELEASE_TIME = 80
MS_EVENTS_SPEED_MULTIPLIER = 1
